# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170124_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(default='', height_field=100, upload_to=None, width_field=100),
        ),
    ]
